### ISSUE TITLE
Module cannot install

### ISSUE THREAD

**Issue by bluegangsta78** [aniketstark/STARK2.0#1]
ation
$ python2 stark.py
Traceback (most recent call last):
  File "stark.py", line 4, in <module>
    from core.starkmcore import *
  File "/data/data/com.termux/files/home/STARK2.0/STARK2.0/core/starkmcore.py", line 5, in <module>
    import request
ImportError: No module named request

Ps. I installed "pip install request" it installed but showing same error , any help sir?

**Comment by aniketstark** [comment]
ok bro i fixing now this issue

**Comment by aniketstark** [comment]
This error was fixed now ok 😅

**Comment by Downey03** [comment]
It shows a indentation error in line 48

**Comment by aniketstark** [comment]
ya i know i fix the check latest
